<?php

namespace Versionable\Prospect\Adapter;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Adapter/AdapterAbstract.php';

/**
 * Test class for AdapterAbstract.
 * Generated by PHPUnit on 2011-04-08 at 08:43:07.
 */
class AdapterAbstractTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var AdapterAbstract
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new AdapterAbstract;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testSetOption().
   */
  public function testSetOption()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
