<?php

namespace Versionable\Prospect\Adapter;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Adapter/Curl.php';

/**
 * Test class for Curl.
 * Generated by PHPUnit on 2011-04-08 at 08:43:07.
 */
class CurlTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Curl
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Curl;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testInitialize().
   */
  public function testInitialize()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCall().
   */
  public function testCall()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testParseResponse().
   */
  public function testParseResponse()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
