<?php

namespace Versionable\Prospect\Adapter;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Adapter/Socket.php';

/**
 * Test class for Socket.
 * Generated by PHPUnit on 2011-04-08 at 08:43:08.
 */
class SocketTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Socket
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Socket;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testInitalize().
   */
  public function testInitalize()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCall().
   */
  public function testCall()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
