<?php

namespace Versionable\Test\Prospect\Adapter;

use Versionable\Prospect\Adapter\CurlFile;

/**
 * Test class for CurlFile.
 * Generated by PHPUnit on 2011-09-22 at 19:27:33.
 */
class CurlFileTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var CurlFile
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new CurlFile;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @todo Implement testCall().
     */
    public function testCall()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
?>
