<?php

namespace Versionable\Prospect\Header;

require_once '/Users/stuart/NetBeansProjects/Http/src/Versionable/Prospect/Header/Accept.php';

/**
 * Test class for Accept.
 * Generated by PHPUnit on 2011-04-08 at 08:43:04.
 */
class AcceptTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Accept
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Accept;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

}

?>
