<?php

namespace Versionable\Prospect\Header;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Header/BasicAuthentication.php';

/**
 * Test class for BasicAuthentication.
 * Generated by PHPUnit on 2011-04-08 at 08:43:05.
 */
class BasicAuthenticationTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var BasicAuthentication
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new BasicAuthentication;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testToString().
   */
  public function testToString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
