<?php

namespace Versionable\Prospect\Header;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Header/Connection.php';

/**
 * Test class for Connection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:06.
 */
class ConnectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Connection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Connection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testSetValue().
   */
  public function testSetValue()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement test__toString().
   */
  public function test__toString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
