<?php
namespace Versionable\Prospect\Header;

/**
 * Test class for Custom.
 * Generated by PHPUnit on 2011-04-06 at 11:51:17.
 */
class CustomTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Custom
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Custom;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }
}
?>
