<?php

namespace Versionable\Prospect\Header;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Header/Header.php';

/**
 * Test class for Header.
 * Generated by PHPUnit on 2011-04-08 at 08:43:04.
 */
class HeaderTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Header
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Header;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testGetName().
   */
  public function testGetName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testSetName().
   */
  public function testSetName()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testGetValue().
   */
  public function testGetValue()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testSetValue().
   */
  public function testSetValue()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testToString().
   */
  public function testToString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement test__toString().
   */
  public function test__toString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
