<?php

namespace Versionable\Prospect\Header;

require_once dirname(__FILE__) . '/../../../../../src/Versionable/Prospect/Header/Pragma.php';

/**
 * Test class for Pragma.
 * Generated by PHPUnit on 2011-04-08 at 08:43:06.
 */
class PragmaTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Pragma
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Pragma;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

}

?>
