<?php

namespace Versionable\Tests\Prospect\Parameter;

use Versionable\Prospect\Parameter\Collection;
use Versionable\Prospect\Parameter\Parameter;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:11.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Collection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Collection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testAdd()
  {
    $parameter = new Parameter('foo', 'bar');
    $this->object->add($parameter);
    
    $elements = $this->readAttribute($this->object, 'elements');
    $this->assertEquals($parameter, $elements['foo']);
  }

  public function test__toString()
  {
    $this->assertEquals($this->object->toString(), (string)$this->object);
  }

  public function testToString()
  {
    
    $parameter = new Parameter('foo', 'bar');
    $this->object->add($parameter);
    
    $parameter = new Parameter('alpha', 'bravo');
    $this->object->add($parameter);
    
    $this->assertEquals('foo=bar&alpha=bravo', $this->object->toString());
  }
  
  public function testIsValidTrue()
  {
      $this->assertTrue($this->object->isValid(new Parameter('foo', 'bar')));
  }

  public function testIsValidFalse()
  {
      $this->assertFalse($this->object->isValid(new \stdClass()));
  }  
  
}
