<?php

namespace Versionable\Tests\Prospect\Url;

use Versionable\Prospect\Url\SoapUrl;

/**
 * Test class for Url.
 * Generated by PHPUnit on 2011-01-05 at 17:48:08.
 */
class SoapUrlTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Url
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new SoapUrl('somepath');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement test__toString().
     */
    public function test__toString()
    {
      $this->assertEquals($this->object->getUrl(), $this->object->__toString());
    }

    /**
     * @todo Implement testToString().
     */
    public function testToString()
    {
      $this->assertEquals($this->object->getUrl(), $this->object->toString());
    }

    /**
     * @todo Implement testGetUrl().
     */
    public function testGetUrl()
    {
      $this->assertEquals($this->object->getUrl(), 'somepath');
    }

    /**
     * @todo Implement testSetUrl().
     */
    public function testSetUrl()
    {
      $url = 'anotherpath';
      $this->object->setUrl($url);
      $this->assertEquals($this->readAttribute($this->object, 'scheme'), 'http');
      $this->assertEquals($this->readAttribute($this->object, 'hostname'), 'localhost');
      $this->assertEquals($this->readAttribute($this->object, 'port'), 80);
      $this->assertEquals($this->readAttribute($this->object, 'parameters'), array());
      $this->assertEquals($this->readAttribute($this->object, 'fragment'), NULL);
    }
}