<?php

namespace Versionable\Tests\Prospect\File;

use Versionable\Prospect\File\Collection;
use Versionable\Prospect\File\File;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:10.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Collection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Collection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testAdd().
   */
  public function testAdd()
  {
    $file = new File('foo', 'bar', 'text/plain');
    $this->object->add($file);
    
    $elements = $this->readAttribute($this->object, 'elements');
    $this->assertEquals($file, $elements['foo']);
  }

  /**
   * @todo Implement testToString().
   */
  public function testToString()
  {    
    $this->object->add(new File('image1', __DIR__ . '/../../../../data/file/file1.txt', 'text/plain'));
    $this->object->add(new File('image2', __DIR__ . '/../../../../data/file/file2.txt', 'text/plain'));
    
    $string = file_get_contents(__DIR__ . '/../../../../data/file/string.txt');
    
    $this->assertEquals($string, $this->object->toString());
  }

  /**
   * @todo Implement testSetBoundary().
   */
  public function testSetBoundary()
  {
    $boundary = 'someboundarytext';
    $this->object->setBoundary($boundary);
    $this->assertEquals($boundary, $this->readAttribute($this->object, 'boundary'));
  }

}
