<?php

namespace Versionable\Tests\Prospect\Cookie;

use Versionable\Prospect\Cookie\Collection;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:10.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Collection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Collection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  /**
   * @todo Implement testAdd().
   */
  public function testAdd()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testRemove().
   */
  public function testRemove()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testGet().
   */
  public function testGet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testHas().
   */
  public function testHas()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement test__toString().
   */
  public function test__toString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testToString().
   */
  public function testToString()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testToArray().
   */
  public function testToArray()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testSetBoundary().
   */
  public function testSetBoundary()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testRewind().
   */
  public function testRewind()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testNext().
   */
  public function testNext()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCurrent().
   */
  public function testCurrent()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testKey().
   */
  public function testKey()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testValid().
   */
  public function testValid()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testCount().
   */
  public function testCount()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testSeek().
   */
  public function testSeek()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testOffsetSet().
   */
  public function testOffsetSet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testOffsetExists().
   */
  public function testOffsetExists()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testOffsetUnset().
   */
  public function testOffsetUnset()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

  /**
   * @todo Implement testOffsetGet().
   */
  public function testOffsetGet()
  {
    // Remove the following lines when you implement this test.
    $this->markTestIncomplete(
    'This test has not been implemented yet.'
    );
  }

}

?>
