<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\AcceptEncoding;

/**
 * Test class for AcceptLanguage.
 * Generated by PHPUnit on 2011-04-08 at 08:43:06.
 */
class AcceptEncodingTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var AcceptEncoding
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new AcceptEncoding;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testConstruct()
  {
      $this->assertEquals('Accept-Encoding', $this->object->getName());
      $this->assertEquals('gzip;q=1.0, identity; q=0.5, *;q=0', $this->object->getValue());
  }

}

