<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\AcceptLanguage;

/**
 * Test class for AcceptLanguage.
 * Generated by PHPUnit on 2011-04-08 at 08:43:06.
 */
class AcceptLanguageTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var AcceptCharset
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new AcceptLanguage;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testConstruct()
  {
      $this->assertEquals('Accept-Language', $this->object->getName());
      $this->assertEquals('en-US', $this->object->getValue());
  }

}

