<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\Accept;

/**
 * Test class for Accept.
 * Generated by PHPUnit on 2011-04-08 at 08:43:04.
 */
class AcceptTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Accept
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Accept;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testToString()
  {
    $string = sprintf('%s: %s', $this->object->getName(), $this->object->getValue());

    $this->assertEquals($string, $this->object->toString());
  }

  public function test__toString()
  {
    $string = sprintf('%s: %s', $this->object->getName(), $this->object->getValue());

    $this->assertEquals($string, (string)$this->object);
  }

  public function testConstruct()
  {
      $this->assertEquals('Accept', $this->object->getName());
      $this->assertEquals('gzip;q=1.0, identity; q=0.5, *;q=0', $this->object->getValue());
  }

}
