<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\BasicAuthentication;

/**
 * Test class for BasicAuthentication.
 * Generated by PHPUnit on 2011-04-08 at 08:43:05.
 */
class BasicAuthenticationTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var BasicAuthentication
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new BasicAuthentication('username', 'password');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testToString()
  {
    $string = sprintf('%s: Basic %s', $this->object->getName(), $this->object->getValue());

    $this->assertEquals($string, $this->object->toString());
  }

  public function test__toString()
  {
    $this->assertEquals($this->object->toString(), (string)$this->object);
  }

  public function testConstruct()
  {
    $this->assertEquals('Authorization', $this->object->getName());
    $this->assertEquals('dXNlcm5hbWU6cGFzc3dvcmQ=', $this->object->getValue());
  }
}
