<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\CacheControl;

/**
 * Test class for CacheControl.
 * Generated by PHPUnit on 2011-04-08 at 08:43:03.
 */
class CacheControlTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var CacheControl
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new CacheControl(100);
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testToString()
  {
    $string = sprintf('%s: max-age=%s', $this->object->getName(), $this->object->getValue());

    $this->assertEquals($string, $this->object->toString());
  }

  public function test__toString()
  {
    $this->assertEquals($this->object->toString(), (string)$this->object);
  }

  public function testConstruct()
  {
      $this->assertEquals('Cache-Control', $this->object->getName());
      $this->assertEquals(100, $this->object->getValue());
  }
}
