<?php

namespace Versionable\Test\Prospect\Header;

use Versionable\Prospect\Header\Collection;
use Versionable\Prospect\Header\Custom;
use Versionable\Prospect\Header\Connection;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:04.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Collection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Collection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }

  public function testAdd()
  {
    $header = new Custom('foo', 'bar');
    $this->object->add($header);
    
    $elements = $this->readAttribute($this->object, 'elements');
    $this->assertEquals($header, $elements['foo']);
  }

  public function testParse()
  {
    $this->object->parse('Connection', 'Close');
    $elements = $this->readAttribute($this->object, 'elements');
    
    $this->assertEquals(new Connection('Close'), $elements['Connection']);
  }
  
  public function testParseToCustom()
  {
    $this->object->parse('Name', 'Prospect');
    $elements = $this->readAttribute($this->object, 'elements');
    
    $this->assertEquals(new Custom('Name', 'Prospect'), $elements['Name']);
  }

}
