<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\ContentType;

/**
 * Test class for ContentType.
 * Generated by PHPUnit on 2011-04-08 at 08:43:05.
 */
class ContentTypeTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var ContentType
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new ContentType('text/html');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testConstruct()
  {
      $this->assertEquals('Content-Type', $this->object->getName());
      $this->assertEquals('text/html', $this->object->getValue());
  }
}

