<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\IPhoneUserAgent;

/**
 * Test class for IPhoneUserAgent.
 * Generated by PHPUnit on 2011-04-08 at 08:43:05.
 */
class IPhoneUserAgentTest extends HeaderTest
{

  /**
   * @var IPhoneUserAgent
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new IPhoneUserAgent;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    
  }
  
}
