<?php

namespace Versionable\Tests\Prospect\Header;

use Versionable\Prospect\Header\IPhoneUserAgent;

/**
 * Test class for IPhoneUserAgent.
 * Generated by PHPUnit on 2011-04-08 at 08:43:05.
 */
class IPhoneUserAgentTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var IPhoneUserAgent
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new IPhoneUserAgent;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    public function testConstruct()
    {
        $this->assertEquals('User-Agent', $this->object->getName());
        $this->assertEquals('Apple iPhone OS 4: Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_0 like Mac OS X; en-us) AppleWebKit/532.9 (KHTML, like Gecko) Version/4.0.5 Mobile/8A293 Safari/6531.22.7', $this->object->getValue());
    }

}
