<?php
namespace Versionable\Http\Browser;


require_once __DIR__ . '/../../../../src/Versionable/Http/Browser/BrowserInterface.php';
require_once __DIR__ . '/../../../../src/Versionable/Http/Browser/Browser.php';

require_once __DIR__ . '/../../../../src/Versionable/Http/Client/HttpInterface.php';
require_once __DIR__ . '/../../../../src/Versionable/Http/History/HistoryInterface.php';

/**
 * Test class for Browser.
 * Generated by PHPUnit on 2011-04-03 at 16:11:50.
 */
class BrowserTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Browser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $http = $this->getMock('Versionable\\Http\\Client\\HttpInterface');
      $history = $this->getMock('Versionable\\Http\\History\\HistoryInterface');

      $this->object = new Browser($http, $history);
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGet().
     */
    public function testGet()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetClient().
     */
    public function testGetClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetClient().
     */
    public function testSetClient()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testGetHistory().
     */
    public function testGetHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }

    /**
     * @todo Implement testSetHistory().
     */
    public function testSetHistory()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
          'This test has not been implemented yet.'
        );
    }
}
?>
