<?php

namespace Versionable\Tests\Prospect\Client;

use Versionable\Prospect\Client\Client;

/**
 * Test class for Client.
 * Generated by PHPUnit on 2010-11-06 at 12:33:37.
 */
class ClientTest extends \PHPUnit_Framework_TestCase {

  /**
   * @var Client
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp() {
    $this->object = new Client;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown() {

  }
  
  public function testConstructorWithAdapter()
  {
    $adapter = $this->getMock('Versionable\Prospect\Adapter\AdapterInterface');
    $object = new Client($adapter);
    $this->assertEquals($adapter, $this->readAttribute($object, 'adapter'));
  }

  public function testSetAdapter() {

    $adapter = $this->getMock('Versionable\Prospect\Adapter\AdapterInterface');
    $this->object->setAdapter($adapter);

    $this->assertEquals($adapter, $this->readAttribute($this->object, 'adapter'));
  }

  public function testGetAdapter() {
    $adapter = $this->getMock('Versionable\Prospect\Adapter\AdapterInterface');
    $this->object->setAdapter($adapter);

    $this->assertEquals($adapter, $this->object->getAdapter());
  }

  public function testSend() {
    $response = $this->getMock('Versionable\Prospect\Response\ResponseInterface');
    $response->expects($this->any())->method('getCode')->will($this->returnValue(200));
    $response->expects($this->any())->method('getContent')->will($this->returnValue('Test content'));
    $response->expects($this->any())->method('getHeaders')->will($this->returnValue(array()));

    $request = $this->getMock('Versionable\Prospect\Request\RequestInterface');

    $adapter = $this->getMock('Versionable\Prospect\Adapter\AdapterInterface');
    $adapter->expects($this->any())->method('call')->will($this->returnValue($response));
    $this->object->setAdapter($adapter);

    $this->assertEquals($response, $this->object->send($request, $response));

  }
}
