<?php

namespace Versionable\Tests\Prospect\Adapter;

use Versionable\Prospect\Cookie\Collection;
use Versionable\Prospect\Cookie\Cookie;

/**
 * Test class for Collection.
 * Generated by PHPUnit on 2011-04-08 at 08:43:13.
 */
class CollectionTest extends \PHPUnit_Framework_TestCase
{

  /**
   * @var Collection
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    $this->object = new Collection;
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {

  }

  public function testAdd()
  {
    $cookie = new Cookie('foo', 'bar');
    $this->object->add($cookie);

    $elements = $this->readAttribute($this->object, 'elements');
    $this->assertEquals($cookie, $elements['foo']);
  }

  public function testIsInvalidTrue()
  {
    $cookie = new Cookie('foo', 'bar');

    $this->assertTrue($this->object->isValid($cookie));

  }

  public function testIsInvalidFalse()
  {
    $this->assertFalse($this->object->isValid(new \stdClass()));
  }

  public function testToString()
  {
    $cookie = new Cookie('foo', 'bar');
    $cookie2 = new Cookie('hey', 'ho');

    $this->object->add($cookie);
    $this->object->add($cookie2);

    $string = $cookie . ';'. $cookie2;
    $this->assertEquals($string, $this->object->toString());
  }

  public function testParse()
  {
    $string = 'foo=bar';
    $cookie = new Cookie('foo', 'bar');

    $new = Cookie::parse($string);

    $this->assertEquals($cookie, $new);
  }
}