<?php
namespace Versionable\Http\Response;

require_once 'src/Versionable/Http/Response/ResponseInterface.php';
require_once 'src/Versionable/Http/Response/Response.php';

/**
 * Test class for Response.
 * Generated by PHPUnit on 2011-04-02 at 15:55:35.
 */
class ResponseTest extends \PHPUnit_Framework_TestCase
{
    /**
     * @var Response
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Response;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @todo Implement testGetCode().
     */
    public function testGetCode()
    {
      $this->object->setCode(418);
      $this->assertEquals($this->readAttribute($this->object, 'code'), $this->object->getCode());
    }

    /**
     * @todo Implement testSetCode().
     */
    public function testSetCode()
    {
      $code = 200;
      $this->object->setCode($code);
      $this->assertEquals($code, $this->readAttribute($this->object, 'code'));
    }
    
    public function testSetCodeInvalid()
    {
      $this->setExpectedException('\\InvalidArgumentException');
      $code = 999;
      $this->object->setCode($code);
    }

    /**
     * @todo Implement testGetContent().
     */
    public function testGetContent()
    {
      $content = "Some content";
      $this->object->setContent($content);
      $this->assertEquals($content, $this->object->getContent());
    }

    /**
     * @todo Implement testSetContent().
     */
    public function testSetContent()
    {
      $content = "Some content";
      $this->object->setContent($content);
      $this->assertEquals($content, $this->readAttribute($this->object, 'content'));
    }

    public function testGetHeaders()
    {
      $headers = $this->getMock('\\Versionable\\Http\\Header\\CollectionInterface');
      $this->object->setHeaders($headers);
      $this->assertEquals($headers, $this->object->getHeaders());
    }

    public function testSetHeaders()
    {
      $headers = $this->getMock('\\Versionable\\Http\\Header\\CollectionInterface');
      $this->object->setHeaders($headers);
      $this->assertEquals($headers, $this->readAttribute($this->object, 'headers'));
    }
    
    public function testGetCookies()
    {
      $cookies = $this->getMock('\\Versionable\\Http\\Cookie\\CollectionInterface');
      $this->object->setCookies($cookies);
      $this->assertEquals($cookies, $this->object->getCookies());
    }

    public function testSetCookies()
    {
      $cookies = $this->getMock('\\Versionable\\Http\\Cookie\\CollectionInterface');
      $this->object->setCookies($cookies);
      $this->assertEquals($cookies, $this->readAttribute($this->object, 'cookies'));
    }
}
